version: '3.3'

services:

  application:
    image:
      users-application-image
    container_name: application
    networks:
      - cloud
    ports:
      - 80:80
    depends_on:
      - database
      - redis
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/app_db"
      - "SPRING_DB_USERNAME=postgres"
      - "SPRING_DB_PASSWORD=qwerty007"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6380"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  database:
    image:
      postgres
    container_name: database
    networks:
      - cloud
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty007
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  redis:
    image:
      redis-filesync
    container_name: redis
    networks:
      - cloud
    ports:
      - 6380:6380
    volumes:
      - redis-volume:/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  pgdata:
    external: true
  redis-volume:
    external: true

networks:
  cloud:
    external: true