GET http://localhost:80/users

###

POST http://localhost:80/users
Content-Type: application/json

{
  "firstname" : "Тайлер",
  "lastname" : "Дёрден"
}

###

POST http://localhost:80/mails
Content-Type: application/json

{
  "emailTo" : "aminovnnnn@list.ru",
  "subject" : "Сэлэм",
  "text" : "Яхшы"
}

###

GET http://localhost:80/mails/basket